name       : dmidecode
version    : '3.2'
release    : 6
source     :
    - http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.2.tar.xz : 077006fa2da0d06d6383728112f2edef9684e9c8da56752e97cd45a11f838edd
license    : GPL-2.0-or-later
component  : system.utils
summary    : Dmidecode reports information about your system's hardware as described in your system BIOS.
description: |
    Dmidecode reports information about your system's hardware as described in your system BIOS according to the SMBIOS/DMI standard (see a sample output). This information typically includes system manufacturer, model name, serial number, BIOS version, asset tag as well as a lot of other details of varying level of interest and reliability depending on the manufacturer.
clang      : no
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
    rm -rf $installdir/usr/share/doc
