name       : dmidecode
version    : 2.12
release    : 2
source     :
    - http://download.savannah.gnu.org/releases/dmidecode/dmidecode-2.12.tar.gz : 5a8214b99c1762f4510bd92baa279336e5fed6e5cd2e418d46d95a4ecc783922
license    : GPL-2.0 
summary    : Dmidecode reports information about your system's hardware as described in your system BIOS.
description: |
    Dmidecode reports information about your system's hardware as described in your system BIOS according to the SMBIOS/DMI standard (see a sample output). This information typically includes system manufacturer, model name, serial number, BIOS version, asset tag as well as a lot of other details of varying level of interest and reliability depending on the manufacturer.
clang      : no
builddeps  :
setup      : |
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
