name       : dmidecode
version    : '3.0'
release    : 4
source     :
    - http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.0.tar.xz : 7ec35bb193729c1d593a1460b59d82d24b89102ab23fd0416e6cf4325d077e45
license    : GPL-2.0
component  : system.utils
summary    : Dmidecode reports information about your system's hardware as described in your system BIOS.
description: |
    Dmidecode reports information about your system's hardware as described in your system BIOS according to the SMBIOS/DMI standard (see a sample output). This information typically includes system manufacturer, model name, serial number, BIOS version, asset tag as well as a lot of other details of varying level of interest and reliability depending on the manufacturer.
clang      : no
setup      : |
    %apply_patches
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
